Resources:
    IntegrationTestTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: RiseFoundationIntegrationTestTable
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
                - AttributeName: pk2
                  AttributeType: S
                - AttributeName: pk3
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: pk2
                  KeySchema:
                      - AttributeName: pk2
                        KeyType: HASH
                      - AttributeName: sk
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: pk3
                  KeySchema:
                      - AttributeName: pk3
                        KeyType: HASH
                      - AttributeName: sk
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
    IntegrationTestS3Bucket:
        Type: 'AWS::S3::Bucket'
        DeletionPolicy: Delete
        Properties:
            BucketName: rise-foundation-integration-test-bucket
    CognitoUserPoolMyUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: RiseFoundationIntegrationTest-pool

            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: true
                InviteMessageTemplate:
                    EmailSubject: You are being invited to join Grandvalley Strawberries
                UnusedAccountValidityDays: 365

    CognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: RiseFoundationIntegrationTest-pool-client
            UserPoolId:
                Ref: CognitoUserPoolMyUserPool
            ExplicitAuthFlows:
                - ADMIN_NO_SRP_AUTH
            GenerateSecret: false
Outputs:
    CognitoUserPoolId:
        Description: Cognito User Pood Id
        Value: !Ref CognitoUserPoolMyUserPool
        Export:
            Name: RiseFoundationIntegrationTest-pool

    CognitoUserPoolClientId:
        Description: Cognito User Pool Client Id
        Value: !Ref CognitoUserPoolClient
        Export:
            Name: RiseFoundationIntegrationTest-pool-client
